### PR TITLE
Turn capstone generator into a list for newer versions of capstone

### PR DESCRIPTION
**Pull request by aidanhs**

### CODE REVIEW

**Comment by MarioVilas** [comment]
Uhm, this patch doesn't seem right... the call to isinstance() will always return False no matter what, since the data is being converted to list. Also I'm pretty sure this breaks older versions of Capstone, and the idea is to make WinAppDbg compatible with all of them if possible (and if not possible then document which versions DO work).

**Comment by aidanhs** [comment]
Not quite. I've reformatted it to try and make it a bit clearer, but it's still a little opaque - feel free to reformat when you merge.

The crucial point is that the call to `list` happens *before* you index into it. We need to do this because (in the version I've just installed of capstone) `capstone.cs_disasm_quick` (and therefore `decoder`) returns a generator rather than a list. In order to be able to index into it with `[0]`, it has to be converted into a list first.
An alternative solution is to call .next on the generator, but given that I assume this used to be a list, that would break backwards compat.

**Comment by aidanhs** [comment]
One minute, my line endings are a bit messed up...

**Comment by aidanhs** [comment]
Ok, good to go. Turns out it wasn't my line endings, it's that all the line endings are /r/n which git on linux doesn't like.

**Comment by MarioVilas** [comment]
But there's still a problem in line 508 - isinstance() is now checking types against a list (if it works at all). You code *only* works on newer versions of the capstone bindings.

**Comment by aidanhs** [comment]
I've left the [0] in there, so we're still taking the first item from the list.

To break it down:
 - `capstone.cs_disasm_quick(capstone.CS_ARCH_X86, capstone.CS_MODE_32, "\x90", 1)` - returns either a list in the old version of capstone or a generator new version of capstone.
 - `list(x)` of above - where x is a list returns the *same* list, where x is a generator returns a list of the items produced by the generator

So:
```
                list(capstone.cs_disasm_quick(
                    capstone.CS_ARCH_X86, capstone.CS_MODE_32, "\x90", 1
                ))[0]
```

returns the first item of the list we've produced, which is the first item of the list/generator returned by cs_disasm_quick.

**Comment by MarioVilas** [comment]
You're absolutely right, I completely misread the code :)

**Pull request merged**
